#ifndef COMUM_H
#define COMUM_H

#define CMDLINE_PARSER_ERROR 50

#define INPUT_ERROR_PORTA_INVALID 51
#define EXIT_SYSCALL_FAILURE 52
#define EXIT_RECVFROM_FAILURE 53
#define EXIT_SENDTO_FAILURE 54
#define INPUT_ERROR_TIMEOUT_INVALID 55


#endif
